### ISSUE TITLE
"create" command seems to be case sensitive

### ISSUE THREAD

**Issue by liamjamesfoley** [hex337/alex-koin-go#25] opened 2021-10-28 04:58 UTC
![image](https://user-images.githubusercontent.com/4086743/139189766-d3436ce2-3c2b-4483-a10b-bf19bbd81aa3.png)

**Comment by hex337** [comment] 2021-10-28 22:50
Hrm... will take a look.

**Comment by hex337** [comment] 2021-10-28 22:57
Ok, so the [regex](https://github.com/hex337/alex-koin-go/blob/main/command/create_coin.go#L15) to parse the command should work. It's case insensitive.

The [process bit](https://github.com/hex337/alex-koin-go/blob/main/command/process.go#L91) which does the routing also looks like it should be case insensitive.

Might have to look at logs to see what happened, but the code makes it look like that _should_ work. I also tried this myself on dev and prod bot, and it works with upper case and lower case and mixed case.

**Comment by hex337** [comment] 2021-12-14 20:45
I think this is now fixed. Going to close since I can't reproduce. For what it's worth, I think this was related to how slack handles spaces, which I created a global fix for.

**Closed as completed by hex337** 2021-12-14 20:45 UTC
